version: '3.8'

services:
  nats-anguve:
    build:
      context: .
      target: prod
      dockerfile: .docker/Dockerfile.prod
    container_name: nats-server-anguve
    restart: always
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - ./server.conf:/etc/nats/server.conf:ro
      - nats_data:/data
      - ./nats/logs:/var/log/nats
    networks:
      - nats_network

networks:
  nats_network:
    driver: bridge

volumes:
  nats_data:
    driver: local
